<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.*" />
    <PackageReference Include="MediatR" Version="12.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
     <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HardwareCatalog.Application\HardwareCatalog.Application.csproj" />
    <ProjectReference Include="..\HardwareCatalog.Infrastructure\HardwareCatalog.Infrastructure.csproj" />
  </ItemGroup>

</Project>
